spring.profiles.active=test

default.sender=edbleonardo@gmail.com
default.recipient=edbleonardo@gmail.com

jwt.secret=essa_minha_chave_precisa_ser_muito_longa_e_segura_com_pelo_menos_64_caracteres
jwt.expiration=11120000